id: IE17F4683
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T20:39:47.685321'
last_modified: '2022-05-27T20:39:47.685332'
parser: null
source_metadata:
  title: TYKYN
  language: ug
  base:
    f9A56:
      title: Complete text
      base_file: f9A56.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
